# VDBFUSION
voxel_size: 0.01
sdf_trunc: 0.07
space_carving: False

# Reconstruction
fill_holes: True
min_weight: 5.0

apply_pose: True
preprocess: True
min_range: 2.0
max_range: 20.0

pcl_topic: "/lidar_undistortion/pointcloud_corrected"

# TF2
parent_frame: "odom"
child_frame: "os1_sensor"
